### ISSUE TITLE
[PE-D][Tester D] Typo under the hint section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-4/tp#162]
![image.png](https://raw.githubusercontent.com/alyssaongyx/ped/main/files/7523de8d-fa79-4e8e-87be-411376c5f64e.png)
Should be hint instead of solve!

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: alyssaongyx/ped#10

**Comment by jinyuan0425** [comment]
Fixed in PR[#201]
