### ISSUE TITLE
[PE-D][Tester D] Output for goals

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-4/tp#172]
![image.png](https://raw.githubusercontent.com/alyssaongyx/ped/main/files/ff67d39e-0989-4bd1-946c-41f00cf2b52b.png)
The goal is 0/2, with the output congratulations.
Can consider using a motivativating tag line :)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: alyssaongyx/ped#14

**Comment by jinyuan0425** [comment]
Fixed initialisation in PR [\#196]
