### ISSUE TITLE
[PE-D][Tester A] random command accepting any parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-4/tp#174]
The app gave me a random card even I have typed a weird command

![image.png](https://raw.githubusercontent.com/Kevin-Liusx/ped/main/files/7e67d6ae-c905-49f5-9917-02679af6371a.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Kevin-Liusx/ped#6

**Comment by jinyuan0425** [comment]
Addressed in PR #214
