### ISSUE TITLE
[PE-D][Tester C] Different types of information on the same line in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-4/tp#177]
In my opinion, description for format and note in this case should be on two seperate lines

![image.png](https://raw.githubusercontent.com/VN-Hao/ped/main/files/d9a8673c-c02c-444d-b0be-8dfb172f7abc.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: VN-Hao/ped#4

**Comment by jinyuan0425** [comment]
Fixed in PR[#201]
