### ISSUE TITLE
[PE-D][Tester A] Set command changes the Due date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-4/tp#179]
when I set the difficulty of a card to a specific level, the due date shown on the card list also changes accordingly to a random date

![image.png](https://raw.githubusercontent.com/Kevin-Liusx/ped/main/files/8827f8cd-4a75-4796-a9f7-cbdf3bc5dcb4.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Kevin-Liusx/ped#7

**Comment by Dioclei** [comment]
Not a bug. This is a feature of the spaced repetition system.
It is already mentioned in the UG, but perhaps it can be made clearer with regards to this.
