### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by GSgiansen** [AY2324S1-CS2103T-W17-4/tp#38]
**Target user profile, value proposition, and user stories:** Update the target user profile and value proposition to match the project direction you have selected. 

**Use cases:** Give use cases (textual form) for a few representative user stories that need multiple steps to complete.

**Non-functional requirements:** Can be project constraints

**Glossary:** Define terms that are worth recording

**Comment by jinyuan0425** [comment]
Included use cases [#42]

**Comment by weeweh** [comment]
Change target user profile, value proposition, user stories, non-functional requirements and glossary to reflect the lessON project in [#41]
